# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6801433787404ac52163a5c16ae3b960577e49d27c56b00968320edad5d034cf1495a73c5085e2153f7d5ea4c912edecde43b685a799794f60a53769de48b61

test:
  secret_key_base: 580fa00fda179e41cf7f940adcde27cbaf0ca3aaf852715a5a1779e704e62e1470bb1eecb9963759f2c0dfd0532e35361fa0985cea46b99c4372b6f51bca0095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
